"""Per-scope Microsoft GraphRAG lifecycle: scaffold, build, status, engine cache.

Ported from paper_read_project_pdf/graphrag_manager.py and restructured for two kinds of
scope that share this same code path:
  * a per-source scope (scope_id == source_id) — exactly one input document.
  * the global cumulative scope (scope_id == config.GLOBAL_SCOPE_ID) — one input file per
    ingested source, accumulated over time (write_source_input is called once per source,
    never overwriting another source's file), so re-ingesting a new source and rebuilding
    folds it into the same growing index.

Builds are heavy (minutes, many LLM calls). serve.py kicks one off in the background after
ingest; chat degrades to vector RAG until the index is ready.
"""
from __future__ import annotations

import json
import sys
import threading
import time
from pathlib import Path
from typing import Any

import config

_REQUIRED = ("entities", "communities", "community_reports", "text_units", "relationships")
_STATUS_FILE = "status.json"

_engines: dict[str, Any] = {}
_locks: dict[str, threading.Lock] = {}
_locks_guard = threading.Lock()

_LOG_MAXLEN = 200
_build_logs: dict[str, list[str]] = {}
_build_logs_lock = threading.Lock()


def root_for(scope_id: str) -> Path:
    return config.DATA_DIR / scope_id / "graphrag"


def _lock_for(scope_id: str) -> threading.Lock:
    with _locks_guard:
        return _locks.setdefault(scope_id, threading.Lock())


def _write_status(root: Path, state: str, message: str = "") -> None:
    root.mkdir(parents=True, exist_ok=True)
    (root / _STATUS_FILE).write_text(
        json.dumps({"state": state, "message": message, "updated_at": time.time()}), encoding="utf-8"
    )


def get_logs(scope_id: str) -> list[str]:
    with _build_logs_lock:
        return list(_build_logs.get(scope_id, []))


def _append_log(scope_id: str, line: str) -> None:
    with _build_logs_lock:
        buf = _build_logs.setdefault(scope_id, [])
        buf.append(line)
        if len(buf) > _LOG_MAXLEN:
            del buf[: len(buf) - _LOG_MAXLEN]


def read_status(scope_id: str) -> dict[str, Any]:
    root = root_for(scope_id)
    if _lock_for(scope_id).locked():
        return {"state": "building", "message": "Rebuilding…"}
    if health(scope_id):
        return {"state": "ready", "message": ""}
    f = root / _STATUS_FILE
    if f.exists():
        try:
            return json.loads(f.read_text(encoding="utf-8"))
        except Exception:
            pass
    return {"state": "idle", "message": ""}


def health(scope_id: str) -> bool:
    out = root_for(scope_id) / "output"
    return all((out / f"{n}.parquet").exists() for n in _REQUIRED)


def _settings_yaml() -> str:
    chat_base = (f"\n    api_base: {config.LLM_BASE_URL}" if config.LLM_BASE_URL else "")
    embed_base = (f"\n    api_base: {config.EMBEDDING_BASE_URL}" if config.EMBEDDING_BASE_URL else "")
    return f"""\
### Generated by graphrag_manager from this app's config. Edit graphrag_manager._settings_yaml
### (or env.txt) rather than hand-editing per-scope copies.

completion_models:
  default_completion_model:
    model_provider: openai
    model: {config.GRAPHRAG_CHAT_MODEL}
    auth_method: api_key
    api_key: ${{GRAPHRAG_API_KEY}}{chat_base}
    retry:
      type: exponential_backoff

embedding_models:
  default_embedding_model:
    model_provider: openai
    model: {config.GRAPHRAG_EMBED_MODEL}
    auth_method: api_key
    api_key: ${{GRAPHRAG_API_KEY}}{embed_base}
    retry:
      type: exponential_backoff

concurrent_requests: {config.GRAPHRAG_CONCURRENT_REQUESTS}

input:
  type: text

chunking:
  type: tokens
  size: 1200
  overlap: 100
  encoding_model: o200k_base

input_storage:
  type: file
  base_dir: "input"

output_storage:
  type: file
  base_dir: "output"

reporting:
  type: file
  base_dir: "logs"

cache:
  type: json
  storage:
    type: file
    base_dir: "cache"

vector_store:
  type: lancedb
  db_uri: output\\lancedb

embed_text:
  embedding_model_id: default_embedding_model

extract_graph:
  completion_model_id: default_completion_model
  prompt: "prompts/extract_graph.txt"
  entity_types: [concept,method,technique,framework,system,architecture,model,tool,application,dataset,metric,organization,person,event]
  max_gleanings: 1

summarize_descriptions:
  completion_model_id: default_completion_model
  prompt: "prompts/summarize_descriptions.txt"
  max_length: 500

extract_graph_nlp:
  text_analyzer:
    extractor_type: regex_english

cluster_graph:
  max_cluster_size: 10

extract_claims:
  enabled: false
  completion_model_id: default_completion_model
  prompt: "prompts/extract_claims.txt"
  description: "Any claims or facts that could be relevant to information discovery."
  max_gleanings: 1

community_reports:
  completion_model_id: default_completion_model
  graph_prompt: "prompts/community_report_graph.txt"
  text_prompt: "prompts/community_report_text.txt"
  max_length: 2000
  max_input_length: 8000

snapshots:
  graphml: false
  embeddings: false

local_search:
  completion_model_id: default_completion_model
  embedding_model_id: default_embedding_model
  prompt: "prompts/local_search_system_prompt.txt"

global_search:
  completion_model_id: default_completion_model
  map_prompt: "prompts/global_search_map_system_prompt.txt"
  reduce_prompt: "prompts/global_search_reduce_system_prompt.txt"
  knowledge_prompt: "prompts/global_search_knowledge_system_prompt.txt"

drift_search:
  completion_model_id: default_completion_model
  embedding_model_id: default_embedding_model
  prompt: "prompts/drift_search_system_prompt.txt"
  reduce_prompt: "prompts/drift_reduce_prompt.txt"

basic_search:
  completion_model_id: default_completion_model
  embedding_model_id: default_embedding_model
  prompt: "prompts/basic_search_system_prompt.txt"
"""


def ensure_settings(scope_id: str) -> Path:
    """Create/refresh a scope's GraphRAG root: settings.yaml + prompts/. Does not touch
    input/ — callers add documents via write_source_input."""
    root = root_for(scope_id)
    (root / "input").mkdir(parents=True, exist_ok=True)
    (root / "prompts").mkdir(parents=True, exist_ok=True)
    (root / "settings.yaml").write_text(_settings_yaml(), encoding="utf-8")

    tmpl = config.GRAPHRAG_TEMPLATE_DIR / "prompts"
    if tmpl.exists():
        for src in tmpl.glob("*.txt"):
            dst = root / "prompts" / src.name
            if not dst.exists():
                dst.write_text(src.read_text(encoding="utf-8"), encoding="utf-8")
    return root


def write_source_input(scope_id: str, source_id: str, text: str) -> None:
    """Write/overwrite this one source's document inside scope_id's input/ dir. Other
    sources' files in the same scope are untouched — this is what lets the global scope
    accumulate documents across many ingests."""
    root = ensure_settings(scope_id)
    (root / "input" / f"{source_id}.txt").write_text(text, encoding="utf-8")


def remove_source_input(scope_id: str, source_id: str) -> None:
    f = root_for(scope_id) / "input" / f"{source_id}.txt"
    if f.exists():
        f.unlink()


def build(scope_id: str) -> None:
    """Build the index in-process (blocking) from whatever is currently in input/."""
    import io
    from contextlib import redirect_stdout, redirect_stderr

    lock = _lock_for(scope_id)
    if not lock.acquire(blocking=False):
        print(f"[graphrag] build already in progress for {scope_id}", file=sys.stderr)
        return
    root = root_for(scope_id)

    with _build_logs_lock:
        _build_logs[scope_id] = []

    class _Tee(io.TextIOBase):
        def __init__(self, real) -> None:
            self._real = real
            self._buf = ""

        def write(self, s: str) -> int:
            self._real.write(s)
            self._buf += s
            while "\n" in self._buf:
                line, self._buf = self._buf.split("\n", 1)
                if line.strip():
                    _append_log(scope_id, line)
            return len(s)

        def flush(self) -> None:
            self._real.flush()
            if self._buf.strip():
                _append_log(scope_id, self._buf)
                self._buf = ""

    try:
        _write_status(root, "building", "Scaffolding GraphRAG root…")
        _append_log(scope_id, "Scaffolding GraphRAG root…")
        ensure_settings(scope_id)
        _write_status(root, "building", "Building knowledge graph (entities, communities, reports)…")
        _append_log(scope_id, "Building knowledge graph — extracting entities, clustering communities, generating reports…")
        print(f"[graphrag] building index for {scope_id} …", file=sys.stderr)
        from graphrag_qa import build_index
        tee_out, tee_err = _Tee(sys.stdout), _Tee(sys.stderr)
        with redirect_stdout(tee_out), redirect_stderr(tee_err):
            build_index(root)
        tee_out.flush(); tee_err.flush()
        _engines.pop(scope_id, None)
        _write_status(root, "ready", "")
        _append_log(scope_id, "Index ready.")
        print(f"[graphrag] index ready for {scope_id}", file=sys.stderr)
    except Exception as e:
        msg = f"{type(e).__name__}: {e}"
        _write_status(root, "failed", msg)
        _append_log(scope_id, f"FAILED: {msg}")
        print(f"[graphrag] build FAILED for {scope_id}: {e}", file=sys.stderr)
    finally:
        lock.release()


def build_async(scope_id: str, force: bool = False) -> bool:
    """Start a background build. Returns True if started.

    force=True is required to pick up newly added/changed input documents on an already
    -healthy root (e.g. every ingest into the global scope), since health() alone can't
    tell that a new source.txt was just dropped into input/.
    """
    if not force and health(scope_id):
        return False
    lock = _lock_for(scope_id)
    if lock.locked():
        return False
    t = threading.Thread(target=build, args=(scope_id,), daemon=True, name=f"graphrag-build-{scope_id}")
    t.start()
    return True


# A single global lock serializes ALL builds across every scope: running graphrag's
# build_index() for two different roots at the same time in this process was observed to
# silently produce an empty output/ for one of the two roots (no exception raised) — some
# state inside the graphrag package isn't safe for concurrent indexing runs.
_global_build_lock = threading.Lock()


def build_sequential_async(scope_ids: list[str], force: bool = False) -> None:
    """Build several scopes one at a time in a single background thread."""
    def run():
        with _global_build_lock:
            for scope_id in scope_ids:
                if not force and health(scope_id):
                    continue
                build(scope_id)
    threading.Thread(target=run, daemon=True, name="graphrag-build-sequential").start()


def get_engine(scope_id: str):
    if not health(scope_id):
        return None
    eng = _engines.get(scope_id)
    if eng is None:
        from graphrag_qa import GraphRAGQA
        eng = GraphRAGQA(root=root_for(scope_id))
        _engines[scope_id] = eng
    return eng


def list_communities(scope_id: str, level: int = 0) -> list[dict[str, Any]] | None:
    eng = get_engine(scope_id)
    if eng is None:
        return None
    import pandas as pd

    communities = eng.communities[eng.communities["level"] == level]
    reports = eng.community_reports.set_index("community")
    out = []
    for row in communities.itertuples():
        report = reports.loc[row.community] if row.community in reports.index else None
        rank = report["rank"] if report is not None else None
        out.append({
            "id": int(row.community), "level": int(row.level), "parent": int(row.parent),
            "children": [int(c) for c in row.children], "title": str(row.title),
            "size": int(row.size), "rank": None if rank is None or pd.isna(rank) else float(rank),
            "summary": str(report["summary"]) if report is not None else "",
        })
    out.sort(key=lambda c: c["size"], reverse=True)
    return out


def get_community_detail(scope_id: str, community_id: int) -> dict[str, Any] | None:
    eng = get_engine(scope_id)
    if eng is None:
        return None
    import pandas as pd

    rows = eng.communities[eng.communities["community"] == community_id]
    if rows.empty:
        return None
    row = rows.iloc[0]
    reports = eng.community_reports[eng.community_reports["community"] == community_id]
    report = reports.iloc[0] if not reports.empty else None

    entity_ids = set(row["entity_ids"].tolist())
    relationship_ids = set(row["relationship_ids"].tolist())
    entities = eng.entities[eng.entities["id"].isin(entity_ids)]
    nodes = [{"id": str(e.title), "label": str(e.title), "type": str(e.type).lower(),
              "description": str(e.description), "frequency": int(e.frequency), "degree": int(e.degree)}
             for e in entities.itertuples()]
    relationships = eng.relationships[eng.relationships["id"].isin(relationship_ids)]
    edges = [{"source": str(r.source), "target": str(r.target), "relation": str(r.description), "weight": float(r.weight)}
             for r in relationships.itertuples()]
    rank = report["rank"] if report is not None else None
    return {
        "community": {
            "id": int(row["community"]), "level": int(row["level"]), "title": str(row["title"]),
            "size": int(row["size"]), "summary": str(report["summary"]) if report is not None else "",
            "full_content": str(report["full_content"]) if report is not None else "",
            "rank": None if rank is None or pd.isna(rank) else float(rank),
        },
        "nodes": nodes, "edges": edges,
    }
